import type { Metadata } from "next";
import "./globals.css";
import { geistSans, instrumentSerif } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Dr. Maya Reynolds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${geistSans.variable} bg-background text-foreground antialiased scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
